//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHATSINH
    {
        public string PHIEU { get; set; }
        public string MAVT { get; set; }
        public int SOLUONG { get; set; }
        public double DONGIA { get; set; }
        public double trigia { get; set; }
    
        public virtual PHATSINH PHATSINH { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
