//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.PHATSINHs = new HashSet<PHATSINH>();
        }
    
        public int MANV { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string PHAI { get; set; }
        public string DIACHI { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public double LUONG { get; set; }
        public string HINH { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHATSINH> PHATSINHs { get; set; }
    }
}
