//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_VATTUEntities : DbContext
    {
        public QL_VATTUEntities()
            : base("name=QL_VATTUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_PHATSINH> CT_PHATSINH { get; set; }
        public virtual DbSet<KHO> KHOes { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHATSINH> PHATSINHs { get; set; }
        public virtual DbSet<VATTU> VATTUs { get; set; }
    
        public virtual ObjectResult<SP_CT_PHATSINH_Result> SP_CT_PHATSINH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CT_PHATSINH_Result>("SP_CT_PHATSINH");
        }
    
        public virtual ObjectResult<SP_CT_PHATSINHbyId_Result> SP_CT_PHATSINHbyId(string maphieu)
        {
            var maphieuParameter = maphieu != null ?
                new ObjectParameter("maphieu", maphieu) :
                new ObjectParameter("maphieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CT_PHATSINHbyId_Result>("SP_CT_PHATSINHbyId", maphieuParameter);
        }
    
        public virtual ObjectResult<SP_DANGNHAP_Result> SP_DANGNHAP(string tENLOGIN)
        {
            var tENLOGINParameter = tENLOGIN != null ?
                new ObjectParameter("TENLOGIN", tENLOGIN) :
                new ObjectParameter("TENLOGIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DANGNHAP_Result>("SP_DANGNHAP", tENLOGINParameter);
        }
    
        public virtual ObjectResult<SP_KHO_Result> SP_KHO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KHO_Result>("SP_KHO");
        }
    
        public virtual ObjectResult<SP_KHObyId_Result> SP_KHObyId(string makho)
        {
            var makhoParameter = makho != null ?
                new ObjectParameter("makho", makho) :
                new ObjectParameter("makho", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KHObyId_Result>("SP_KHObyId", makhoParameter);
        }
    
        public virtual ObjectResult<SP_NHANVIEN_Result> SP_NHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NHANVIEN_Result>("SP_NHANVIEN");
        }
    
        public virtual ObjectResult<SP_NHANVIENbyId_Result> SP_NHANVIENbyId(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NHANVIENbyId_Result>("SP_NHANVIENbyId", manvParameter);
        }
    
        public virtual ObjectResult<SP_PHATSINH_Result> SP_PHATSINH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PHATSINH_Result>("SP_PHATSINH");
        }
    
        public virtual ObjectResult<SP_PHATSINHbyId_Result> SP_PHATSINHbyId(string maphieu)
        {
            var maphieuParameter = maphieu != null ?
                new ObjectParameter("maphieu", maphieu) :
                new ObjectParameter("maphieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PHATSINHbyId_Result>("SP_PHATSINHbyId", maphieuParameter);
        }
    
        public virtual ObjectResult<sp_PhieuNvLapTrongNamTheoLoai__Result> sp_PhieuNvLapTrongNamTheoLoai_(Nullable<int> mANV, string lOAI, Nullable<int> nAM)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var lOAIParameter = lOAI != null ?
                new ObjectParameter("LOAI", lOAI) :
                new ObjectParameter("LOAI", typeof(string));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PhieuNvLapTrongNamTheoLoai__Result>("sp_PhieuNvLapTrongNamTheoLoai_", mANVParameter, lOAIParameter, nAMParameter);
        }
    
        public virtual ObjectResult<SP_SLTON_VATTU_Result> SP_SLTON_VATTU(string mAVT)
        {
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SLTON_VATTU_Result>("SP_SLTON_VATTU", mAVTParameter);
        }
    
        public virtual ObjectResult<SP_VATTU_Result> SP_VATTU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VATTU_Result>("SP_VATTU");
        }
    
        public virtual ObjectResult<SP_VATTUbyId_Result> SP_VATTUbyId(string mavt)
        {
            var mavtParameter = mavt != null ?
                new ObjectParameter("mavt", mavt) :
                new ObjectParameter("mavt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VATTUbyId_Result>("SP_VATTUbyId", mavtParameter);
        }
    
        public virtual int SP_InsertVattu(string mavt, string tenvt, string dvt)
        {
            var mavtParameter = mavt != null ?
                new ObjectParameter("mavt", mavt) :
                new ObjectParameter("mavt", typeof(string));
    
            var tenvtParameter = tenvt != null ?
                new ObjectParameter("tenvt", tenvt) :
                new ObjectParameter("tenvt", typeof(string));
    
            var dvtParameter = dvt != null ?
                new ObjectParameter("dvt", dvt) :
                new ObjectParameter("dvt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertVattu", mavtParameter, tenvtParameter, dvtParameter);
        }
    
        public virtual int SP_UpdateVattu(string mavt, string tenvt, string dvt)
        {
            var mavtParameter = mavt != null ?
                new ObjectParameter("mavt", mavt) :
                new ObjectParameter("mavt", typeof(string));
    
            var tenvtParameter = tenvt != null ?
                new ObjectParameter("tenvt", tenvt) :
                new ObjectParameter("tenvt", typeof(string));
    
            var dvtParameter = dvt != null ?
                new ObjectParameter("dvt", dvt) :
                new ObjectParameter("dvt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateVattu", mavtParameter, tenvtParameter, dvtParameter);
        }
    
        public virtual int SP_DeleteVattu(string mavt)
        {
            var mavtParameter = mavt != null ?
                new ObjectParameter("mavt", mavt) :
                new ObjectParameter("mavt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteVattu", mavtParameter);
        }
    }
}
